parameters:

    ccdn_component_crumb.trail.class: CCDNComponent\CrumbTrailBundle\Component\Crumb

services:

    #
    # Crumb Trail Component.
    #
    ccdn_component_crumb.trail:
        class:      %ccdn_component_crumb.trail.class%
        arguments:  [@templating]
