parameters:

    # Service Parameters defined in app/config

services:

    #
    # Crumb Trail Component.
    #
    ccdn_component_crumb_trail.component.trail:
        class: %ccdn_component_crumb_trail.component.trail.class%
        arguments:
            - @templating
