parameters:
    ccdn_component_crumb_trail.crumb_trail.class: CCDNComponent\CrumbTrailBundle\Controller\CrumbTrailController
    
services:
    ccdn_component_crumb_trail.crumb_trail:
        class:      %ccdn_component_crumb_trail.crumb_trail.class%
        arguments:  [@templating]